services:
  db:
    image: docker.io/mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=prisma_password
      - MYSQL_DATABASE=FL2025_SWE
      - MYSQL_USER=prisma
      - MYSQL_PASSWORD=prisma_password
  app:
    env_file: ".env"
    environment:
      - NEXT_WEBPACK_USE=1
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: frontend
    command: npm run dev
    volumes: # need volume for database container so that the visuals are not removed every time the db is restarted
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db