---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-draft
  labels:
    app: project-draft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-draft
  template:
    metadata:
      labels:
        app: project-draft
    spec:
      containers:
        - name: project-draft
          image: myapp:release-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: mysql://isha:isha@db:3306/fl2025_group_5
